using System.Text.Json;
using AmoSave.Kite.API.Data;
using AmoSave.Kite.API.Models;
using AmoSave.Kite.API.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace AmoSave.Kite.API.Controllers;

[ApiController]
[Route("api/[controller]")]
[Produces("application/json")]
public class OrderController : ControllerBase
{
    private readonly IKiteConnectService _kite;
    private readonly KiteDbContext _db;
    private readonly KiteConnectSettings _settings;
    private readonly ILogger<OrderController> _logger;

    public OrderController(IKiteConnectService kite, KiteDbContext db, IOptions<KiteConnectSettings> settings, ILogger<OrderController> logger)
    {
        _kite = kite;
        _db = db;
        _settings = settings.Value;
        _logger = logger;
    }

    /// <summary>Returns all orders for the day. Fetched from cache if fresh, otherwise from Kite Connect.</summary>
    [HttpGet]
    public async Task<ActionResult<ApiResponse<object>>> GetOrders(
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken)
    {
        try
        {
            var expiry = DateTime.UtcNow.AddMinutes(-_settings.CacheExpiryMinutes);
            var cached = await _db.Orders
                .Where(o => o.UserId == userId && o.CachedAt > expiry)
                .ToListAsync();

            if (cached.Count > 0)
                return Ok(ApiResponse<object>.Success(cached));

            var result = await _kite.GetOrdersAsync(accessToken);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            await SyncOrdersAsync(userId, data);
            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get orders for user {UserId}", userId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Returns the history of a specific order including all state transitions.</summary>
    [HttpGet("{orderId}/history")]
    public async Task<ActionResult<ApiResponse<object>>> GetOrderHistory(
        string orderId,
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken)
    {
        try
        {
            var result = await _kite.GetOrderHistoryAsync(accessToken, orderId);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get order history for {OrderId}", orderId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Returns all trades generated by a specific order.</summary>
    [HttpGet("{orderId}/trades")]
    public async Task<ActionResult<ApiResponse<object>>> GetOrderTrades(
        string orderId,
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken)
    {
        try
        {
            var cached = await _db.Trades
                .Where(t => t.OrderId == orderId && t.UserId == userId)
                .ToListAsync();

            if (cached.Count > 0)
                return Ok(ApiResponse<object>.Success(cached));

            var result = await _kite.GetOrderTradesAsync(accessToken, orderId);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get trades for order {OrderId}", orderId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Returns all trades for the day.</summary>
    [HttpGet("trades")]
    public async Task<ActionResult<ApiResponse<object>>> GetTrades(
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken)
    {
        try
        {
            var expiry = DateTime.UtcNow.AddMinutes(-_settings.CacheExpiryMinutes);
            var cached = await _db.Trades
                .Where(t => t.UserId == userId && t.CachedAt > expiry)
                .ToListAsync();

            if (cached.Count > 0)
                return Ok(ApiResponse<object>.Success(cached));

            var result = await _kite.GetTradesAsync(accessToken);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get trades for user {UserId}", userId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Places a new order.</summary>
    [HttpPost]
    public async Task<ActionResult<ApiResponse<object>>> PlaceOrder(
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken,
        [FromBody] PlaceOrderRequest request)
    {
        try
        {
            var orderParams = BuildOrderParams(request);
            var result = await _kite.PlaceOrderAsync(accessToken, request.Variety, orderParams);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            _logger.LogInformation("Order placed for user {UserId}: {OrderId}", userId,
                data.TryGetProperty("order_id", out var oid) ? oid.GetString() : "unknown");

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to place order for user {UserId}", userId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Modifies an open or pending order.</summary>
    [HttpPut("{orderId}")]
    public async Task<ActionResult<ApiResponse<object>>> ModifyOrder(
        string orderId,
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken,
        [FromBody] ModifyOrderRequest request)
    {
        try
        {
            var orderParams = new Dictionary<string, string>();
            if (request.Quantity.HasValue) orderParams["quantity"] = request.Quantity.Value.ToString();
            if (request.Price.HasValue) orderParams["price"] = request.Price.Value.ToString();
            if (request.TriggerPrice.HasValue) orderParams["trigger_price"] = request.TriggerPrice.Value.ToString();
            if (request.DisclosedQuantity.HasValue) orderParams["disclosed_quantity"] = request.DisclosedQuantity.Value.ToString();
            if (request.Validity != null) orderParams["validity"] = request.Validity;
            if (request.OrderType != null) orderParams["order_type"] = request.OrderType;

            var result = await _kite.ModifyOrderAsync(accessToken, request.Variety, orderId, orderParams);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to modify order {OrderId}", orderId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    /// <summary>Cancels an open or pending order.</summary>
    [HttpDelete("{orderId}")]
    public async Task<ActionResult<ApiResponse<object>>> CancelOrder(
        string orderId,
        [FromHeader(Name = "X-User-Id")] string userId,
        [FromHeader(Name = "X-Access-Token")] string accessToken,
        [FromQuery] string variety = "regular",
        [FromQuery] string? parentOrderId = null)
    {
        try
        {
            var result = await _kite.CancelOrderAsync(accessToken, variety, orderId, parentOrderId);
            if (!IsSuccess(result, out var data))
                return BadRequest(ApiResponse<object>.Error(GetErrorMessage(result)));

            return Ok(ApiResponse<object>.Success(data));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to cancel order {OrderId}", orderId);
            return StatusCode(500, ApiResponse<object>.Error(ex.Message));
        }
    }

    private async Task SyncOrdersAsync(string userId, JsonElement data)
    {
        await _db.Orders.Where(o => o.UserId == userId).ExecuteDeleteAsync();
        if (data.ValueKind != JsonValueKind.Array) return;

        foreach (var item in data.EnumerateArray())
        {
            _db.Orders.Add(new Order
            {
                OrderId = GetString(item, "order_id"),
                UserId = userId,
                ExchangeOrderId = GetString(item, "exchange_order_id"),
                ParentOrderId = GetString(item, "parent_order_id"),
                Status = GetString(item, "status"),
                StatusMessage = GetString(item, "status_message"),
                TradingSymbol = GetString(item, "tradingsymbol"),
                Exchange = GetString(item, "exchange"),
                InstrumentToken = GetString(item, "instrument_token"),
                OrderType = GetString(item, "order_type"),
                TransactionType = GetString(item, "transaction_type"),
                Validity = GetString(item, "validity"),
                Product = GetString(item, "product"),
                Quantity = GetInt(item, "quantity"),
                PendingQuantity = GetInt(item, "pending_quantity"),
                FilledQuantity = GetInt(item, "filled_quantity"),
                DisclosedQuantity = GetInt(item, "disclosed_quantity"),
                Price = GetDecimal(item, "price"),
                TriggerPrice = GetDecimal(item, "trigger_price"),
                AveragePrice = GetDecimal(item, "average_price"),
                Tag = GetString(item, "tag"),
                Variety = GetString(item, "variety"),
                CachedAt = DateTime.UtcNow
            });
        }
        await _db.SaveChangesAsync();
    }

    private static Dictionary<string, string> BuildOrderParams(PlaceOrderRequest request)
    {
        var p = new Dictionary<string, string>
        {
            ["exchange"] = request.Exchange,
            ["tradingsymbol"] = request.TradingSymbol,
            ["transaction_type"] = request.TransactionType,
            ["quantity"] = request.Quantity.ToString(),
            ["product"] = request.Product,
            ["order_type"] = request.OrderType,
            ["validity"] = request.Validity
        };
        if (request.Price.HasValue) p["price"] = request.Price.Value.ToString();
        if (request.TriggerPrice.HasValue) p["trigger_price"] = request.TriggerPrice.Value.ToString();
        if (request.DisclosedQuantity.HasValue) p["disclosed_quantity"] = request.DisclosedQuantity.Value.ToString();
        if (!string.IsNullOrEmpty(request.Tag)) p["tag"] = request.Tag;
        return p;
    }

    private static bool IsSuccess(JsonElement element, out JsonElement data)
    {
        if (element.TryGetProperty("status", out var status) && status.GetString() == "success"
            && element.TryGetProperty("data", out data))
            return true;
        data = default;
        return false;
    }

    private static string GetErrorMessage(JsonElement element) =>
        element.TryGetProperty("message", out var msg) ? msg.GetString() ?? "Unknown error" : "Unknown error";

    private static string GetString(JsonElement element, string property) =>
        element.TryGetProperty(property, out var prop) && prop.ValueKind != JsonValueKind.Null
            ? prop.GetString() ?? "" : "";

    private static int GetInt(JsonElement element, string property) =>
        element.TryGetProperty(property, out var prop) && prop.ValueKind == JsonValueKind.Number
            ? prop.GetInt32() : 0;

    private static decimal GetDecimal(JsonElement element, string property) =>
        element.TryGetProperty(property, out var prop) && prop.ValueKind == JsonValueKind.Number
            ? prop.GetDecimal() : 0m;
}
